import fs from "node:fs";
import path from "node:path";

const [summaryPath, reportPath = "load-tests/results/client-load-test-report.md"] = process.argv.slice(2);
if (!summaryPath) throw new Error("Usage: node load-tests/render-report.mjs <summary.json> [report.md]");
const summary = JSON.parse(fs.readFileSync(summaryPath, "utf8"));
const metric = (name, field) => summary.metrics?.[name]?.values?.[field] ?? "N/A";
const number = (value, decimals = 2) => typeof value === "number" ? value.toFixed(decimals) : value;
const vus = metric("vus_max", "max") || metric("vus", "max");
const p95 = metric("http_req_duration", "p(95)");
const p99 = metric("http_req_duration", "p(99)");
const failureRate = metric("http_req_failed", "rate");
const pass = typeof failureRate === "number" && failureRate < 0.01 && typeof p95 === "number" && p95 < 1500;

const report = `# KnowAllEdge API load-test report

## Executive summary

- Result: **${pass ? "PASS" : "REVIEW REQUIRED"}**
- Peak concurrent virtual users: **${number(vus, 0)}**
- HTTP request failure rate: **${typeof failureRate === "number" ? `${number(failureRate * 100)}%` : "N/A"}**
- HTTP response time: p95 **${number(p95)} ms**; p99 **${number(p99)} ms**

## Scope and controls

This authorized run exercised read-only public browsing and, when a dedicated test account was supplied, authenticated read-only browsing. It did not call signup, password, upload, saved-news toggle, quiz submission, or any admin mutation APIs. The runner must record the target, UTC window, profile, deployment version, AWS resource metrics, and k6 command below before this document is sent externally.

| Field | Recorded value |
| --- | --- |
| Target API | _Complete before delivery_ |
| Test date/time (UTC) | _Complete before delivery_ |
| Load profile | _Complete before delivery_ |
| Deployment/version | _Complete before delivery_ |
| Peak concurrent virtual users | ${number(vus, 0)} |
| Requests | ${number(metric("http_reqs", "count"), 0)} |
| Failure rate | ${typeof failureRate === "number" ? `${number(failureRate * 100)}%` : "N/A"} |
| Mean response time | ${number(metric("http_req_duration", "avg"))} ms |
| p95 / p99 response time | ${number(p95)} ms / ${number(p99)} ms |

## Capacity statement

The service sustained **${number(vus, 0)} concurrent virtual users** only if the test passed the agreed service objectives: less than 1% failed HTTP requests, p95 under 1.5 seconds, and p99 under 3 seconds. A result outside those limits is not a capacity approval; investigate the endpoint and AWS/MongoDB metrics before increasing the load.

"Concurrent virtual users" is the controlled load generated by k6, not the number of distinct real customers. Real active users are reported separately by the deployed, authenticated heartbeat metric: 5-minute active users, DAU, and WAU.

## AWS and database evidence to attach

- Load balancer: request count, target response time, HTTP 4xx/5xx, healthy hosts.
- Compute: CPU, memory, network, restarts, and autoscaling events.
- MongoDB: CPU, connections, operations/second, query latency, disk I/O, and slow queries.
- Application logs: error count grouped by endpoint and timestamps aligned to the run.

## Recommendation

${pass ? "Approve this profile as the verified baseline, then run the next profile during an approved maintenance window." : "Do not publish a capacity figure yet. Review failed endpoints and AWS/MongoDB saturation, remediate, and repeat the same profile."}
`;

fs.mkdirSync(path.dirname(reportPath), { recursive: true });
fs.writeFileSync(reportPath, report);
console.log(`Wrote ${reportPath}`);
